export const LOADING_BILLS = 'LOADING_BILLS';
export const LOADED_BILLS = 'LOADED_BILLS';
export const ERROR_BILLS = 'ERROR_BILLS';
export const LOADING_CATEGORIES = 'LOADING_CATEGORIES';
export const LOADED_CATEGORIES = 'LOADED_CATEGORIES';
export const ERROR_CATEGORIES = 'ERROR_CATEGORIES';
export const UPDATED_BILL = 'UPDATED_BILL';
